### ISSUE TITLE
File name change in latest TRUD SNOMED-CT files

### ISSUE THREAD

**Issue by ewenharrison** [anoopshah/Rdiagnosislist#6]
Hi Anoop,
Many thanks for all your work on this. 
`loadSNOMED()` is not finding the up-to-date UK file for us, I presume because of a change in the naming convention. 
Happy to PR and adjust - but you are likely to be able to sort it quicker?
Many thanks again. 
Ewen
Edinburgh

----
`SnomedCT_UKClinicalRF2_PRODUCTION_20220511T000001Z/Snapshot/Terminology/sct2_Concept_UKCLSnapshot_GB1000000_20220511.txt`

No longer `_Concept_Snapshot`.

**Comment by fabp5** [comment]
Hi Anoop,

Thanks for your work on this package, I'm finding it very useful. Regarding the issue caused by the file name changes in TRUD, would changing the pattern in the same way for the refset tables allow these tables to be found too? i.e.: 
```
Refset_SimpleMap.*Snapshot|SIMPLEMAP
Refset_ExtendedMap.*Snapshot|EXTENDEDMAP
Refset_Simple.*Snapshot|REFSET
```

This seems to work for me when I edit the function. There may be more to it, but if it's helpful I'm happy to PR.

Freya

**Comment by anoopshah** [comment]
Dear Freya,

Thanks for your feedback and glad you are finding the package useful. If
you can make a pull request that would be helpful, but otherwise I will
correct this as soon as I can.

Thank you,

Anoop

**Comment by fabp5** [comment]
Thanks Anoop - have done. This seems to work for the refset files in the UK edition and the monolith edition.
